"""
BodyState - Centralized robot state container

Architecture core: All modules communicate through BodyState instead of calling each other directly.

Design principles:
  - Single Source of Truth
  - All controllers read/write the same state
  - Module decoupling via indirect state-based communication

State categories:
  1. motion_intent  - Motion intent (forward, turn, mode)
  2. imu           - IMU sensor data
  3. body_pose     - Body pose offsets
  4. gait          - Gait state
  5. locomotion    - Locomotion mixed state
  6. runtime       - Runtime state
"""
from calibration import POSE_MIXER, LOCOMOTION


class BodyState:
    """
    Centralized robot state container

    Usage:
        body = BodyState()
        body.motion_intent['forward_velocity'] = 0.5
        body.imu['pitch'] = 1.2
        pose = body.compute_final_pose()
    """

    def __init__(self):
        # === 1. Motion Intent ===
        # Intent parsed from remote control input
        self.motion_intent = {
            'forward_velocity': 0.0,    # [-1.0, 1.0]
            'turn_velocity': 0.0,        # [-1.0, 1.0]
            'mode': 1,                    # 0=vehicle, 1=crawl (walking)
            'emergency_stop': False,
        }

        # === 2. IMU (Sensor Data) ===
        self.imu = {
            'pitch': 0.0,        # Pitch angle (degrees)
            'roll': 0.0,          # Roll angle (degrees)
            'yaw': 0.0,           # Yaw angle (degrees)
            'pitch_rate': 0.0,    # Pitch angular velocity (deg/s)
            'roll_rate': 0.0,      # Roll angular velocity (deg/s)
            'yaw_rate': 0.0,       # Yaw angular velocity (deg/s)
            'accel_x': 0.0,
            'accel_y': 0.0,
            'accel_z': 0.0,
            'valid': False,          # Whether IMU data is valid
        }

        # === 3. Body Pose Offsets ===
        # Written by stabilizer / suspension / animation modules
        self.body_pose = {
            'pitch_offset': 0.0,    # Body pitch offset (degrees)
            'roll_offset': 0.0,     # Body roll offset (degrees)
            'yaw_offset': 0.0,      # Body yaw offset (degrees)
            'height_offset': 0.0,   # Body height offset (degrees, mapped to leg length)
            'source': None,           # Offset source (for debugging)
        }

        # === 4. Gait State ===
        self.gait = {
            'phase': 0.0,             # Current gait phase [0.0, 1.0)
            'gait_type': 'single',     # Current gait type
            'current_velocity': 0.0,   # Current smoothed velocity
            'step_length': 90,         # Step length (degrees)
            'step_height': 45,         # Step height (degrees)
        }

        # === 5. Locomotion (Mixed Motion State) ===
        self.locomotion = {
            'forward': 0.0,           # Smoothed forward velocity
            'turn': 0.0,              # Smoothed turn velocity
            'speed': 0.0,             # Combined speed = sqrt(forward² + turn²)
            'leg_scales': [0.0] * 4, # Per-leg stride scale factor
        }

        # === 6. Runtime ===
        self.runtime = {
            'dt': 0.01,              # Current time step (seconds)
            'timestamp': 0.0,          # Current timestamp (seconds)
            'loop_count': 0,           # Main loop counter
            'enabled_controllers': [],  # Currently enabled controllers
        }

        # === 7. Pose Layers ===
        # Each controller writes its own pose contribution
        # PoseMixer performs the final blend
        self.pose_layers = {
            'gait': None,          # Pose generated by gait
            'stabilizer': None,    # Stabilizer correction
            'suspension': None,    # Suspension correction
            'animation': None,     # Future: animation layer
            'manual': None,        # Future: manual override layer
        }

        # === 8. Controller Weights ===
        # Prevents any single controller from dominating others
        self.weights = {
            'gait': 1.0,            # Gait weight (usually full authority)
            'stabilizer': POSE_MIXER.get('stabilizer_weight', 0.3),
            'suspension': POSE_MIXER.get('suspension_weight', 0.5),
            'animation': 0.0,         # Disabled by default
            'manual': 0.0,            # Disabled by default
        }

    def update_imu(self, pitch, roll, yaw=0.0, dt=0.01):
        """Update IMU data"""
        self.imu['pitch'] = pitch
        self.imu['roll'] = roll
        self.imu['yaw'] = yaw
        self.imu['valid'] = True

    def update_motion_intent(self, forward, turn, mode=None):
        """Update motion intent"""
        self.motion_intent['forward_velocity'] = forward
        self.motion_intent['turn_velocity'] = turn
        if mode is not None:
            self.motion_intent['mode'] = mode

    def update_gait_state(self, phase, gait_type, velocity):
        """Update gait state"""
        self.gait['phase'] = phase
        self.gait['gait_type'] = gait_type
        self.gait['current_velocity'] = velocity

    def update_locomotion(self, forward, turn, leg_scales):
        """Update locomotion mixed state"""
        from math import sqrt, copysign
        self.locomotion['forward'] = forward
        self.locomotion['turn'] = turn
        mag = sqrt(forward ** 2 + turn ** 2)
        self.locomotion['speed'] = copysign(mag, forward) if forward != 0 else 0.0
        self.locomotion['leg_scales'] = leg_scales

    def set_pose_layer(self, layer_name, pose):
        """
        Set a pose layer

        :param layer_name: 'gait', 'stabilizer', 'suspension', etc.
        :param pose: dict {leg: {'rot':, 'lift':}}
        """
        if layer_name in self.pose_layers:
            self.pose_layers[layer_name] = pose

    def compute_final_pose(self):
        """
        Compute the final blended pose

        Formula:
            final_pose = Σ (layer_pose * weight)

        Returns:
            {leg: {'rot':, 'lift':}}
        """
        final = {}
        for leg in ['FR', 'BR', 'BL', 'FL']:
            final[leg] = {'rot': 0.0, 'lift': 0.0}

        for layer_name, weight in self.weights.items():
            layer_pose = self.pose_layers.get(layer_name)
            if layer_pose is None or weight == 0.0:
                continue

            for leg in final:
                if leg in layer_pose:
                    final[leg]['rot'] += layer_pose[leg].get('rot', 0.0) * weight
                    final[leg]['lift'] += layer_pose[leg].get('lift', 0.0) * weight

        return final

    def reset(self):
        """Reset all state (called on emergency stop or mode switch)"""
        self.motion_intent['forward_velocity'] = 0.0
        self.motion_intent['turn_velocity'] = 0.0
        self.locomotion['forward'] = 0.0
        self.locomotion['turn'] = 0.0
        self.body_pose['pitch_offset'] = 0.0
        self.body_pose['roll_offset'] = 0.0
        self.body_pose['height_offset'] = 0.0
        for key in self.pose_layers:
            self.pose_layers[key] = None

    def summary(self):
        """Return current state summary (for debugging)"""
        return {
            'motion': self.motion_intent,
            'imu': self.imu,
            'body': self.body_pose,
            'gait': self.gait,
            'locomotion': self.locomotion,
        }
